
# 编译器的种类
# CLANG = clang++
# GCC = g++

# # 编译器的选择
# CC = ${CLANG}
# # 编译参数
# CPPFLAGS = -std=c++11 -pthread -g
# # 链接参数
# LIBS = -Wl, --no-as-needed -lpthread -pthread
# # 源文件
# SRC = 

.DELETE_ON_ERROR:
all: one two

one:
	touch one
	false

two:
	touch two
	false